version: "3.7"

services:
  admin:
    image: nginx:1.25.3
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app/api:/api
      - ./app/admin:/admin
      - ./configs/nginx:/etc/nginx/conf.d:ro
    networks:
      - mms

  api:
    build: docker/php
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./app/api:/api
      - ./configs/system/dev.yml:/api/config.yml:ro
    networks:
      - mms

  tools:
    build: docker/tools
    restart: unless-stopped
    volumes:
      - ./app/api:/api
      - ./configs/system/dev.yml:/api/config.yml:ro
    networks:
      - mms

  db:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    networks:
      - mms

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mms

volumes:
  db:

networks:
  mms:
    driver: bridge
